### ISSUE TITLE
No text on plots when sanitize=TRUE (when using pgfSweave)

### ISSUE THREAD

**Issue by mlt** [Sharpie/RTikZDevice#15] opened 2010-10-13 04:01 UTC
I'm using lattice to produce plots. I decided to give a try to sanitize text strings. However resulting tikz files miss all my text at all :(

**Comment by cameronbracken** [comment] 2010-10-13 04:18
Yeah, this is a known issue, the bug has been fixed in the next release of tikzDevice (which has been submitted to CRAN).  In the meantime you can get it from R-Forge:

```
install.packages('tikzDevice',repos='http://r-forge.r-project.org')
```

**Comment by cameronbracken** [comment] 2010-10-13 04:21
Please see: http://github.com/Sharpie/RTikZDevice/issues/unreads#issue/14

For possible complications if you are building from source.

**Comment by Sharpie** [comment] 2010-10-13 04:26
Aye, this has been fixed in `0.5.1` which was added to CRAN yesterday and will probably be available tomorrow.

**Closed as completed** 2010-10-13 11:26 UTC

**Comment by mlt** [comment] 2010-10-13 17:41
I updated packages from CRAN (tikzDevice 0.5.1) and now R (2.11.1) crashes badly :( Last words were:

pgfsweave-script.R: pgfSweave version 1.0.9
dvi:              FALSE
pgfsweave-only:   FALSE
graphics-only:    FALSE

Writing to file vignette.tex
Processing code chunks ...
 1 : echo term verbatim (label=load)
Loading required package: RColorBrewer
Loading required package: lattice
 2 : echo term verbatim (label=usgs)
 3 : echo term verbatim (label=exc)
 4 : echo term verbatim (label=mv)
 5 : echo term verbatim tikz sanitize (label=mv_fig)
Creating temporary TikZ metrics dictionary at:
        C:\DOCUME~1\user\LOCALS~1\Temp\Rtmp52vg3A/tikzMetricsDictionary
Error: no function to return from, jumping to top level
Execution halted

**Comment by cameronbracken** [comment] 2010-10-13 17:49
Would it be possible to provide a sample document that causes the crash?  I'm not sure if this problem is tikzDevice or pgfSweave and it would be helpful to track down the problem.

**Comment by mlt** [comment] 2010-10-13 18:07
tikz though has final lines, but it looks incomplete. I'm not positive if it is pgfSweave or tikzDevice problem.
Here is the link to zip file with everything necessary inside: http://www.sendspace.com/file/obbg5h
runme.Rnw fails while source('runme.R') should be fine

**Comment by cameronbracken** [comment] 2010-10-13 18:39
Something is definitely weird and I'm not sure what is causing it.  A few things:
- I was able to reproduce the crash in the GUI
- I was not able to reproduce it with R CMD pgfsweave (everything worked fine)
- It seems to be related to the tikzDevice string metrics caching.  If I set a specific file for the dictionary `options(tikzMetricsDictionary = "/Users/cameron/.tikzMetricsDictionary")`  then I do not get the crash.  That may be a viable workaround for now until I can track down the problem.

**Comment by Sharpie** [comment] 2010-10-13 18:46
Opening a separate issue as this is not related to string sanitization.

**Comment by mlt** [comment] 2010-10-13 18:52
Sharpie, did you already open new issue or do you suggest to open? I didn't see any looking alike.

P.S. Rscript fails even if I provide different path for tikzMetricsDictionary

**Comment by Sharpie** [comment] 2010-10-13 18:53
Yeah, just opened as [issue 16](http://github.com/Sharpie/RTikZDevice/issues#issue/16).
